export const actors = [
  {
    id: "1",
    firstName: "Autumn",
    lastName: "Phillips",
    gender: "female",
    lives: "New York, USA",
    playingAge: { min: 25, max: 30 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_1.png",
    job: "Psychiatric technician",
    category: "filmActors",
  },
  {
    id: "2",
    firstName: "Chris",
    lastName: "Glasser",
    gender: "male",
    lives: "Chicago, USA",
    playingAge: { min: 30, max: 35 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_3.png",
    job: "Power lineman",
    category: "seriesActors",
  },
  {
    id: "3",
    firstName: "Kimberly",
    lastName: "Mastran",
    gender: "female",
    lives: "Los Angeles, USA",
    playingAge: { min: 28, max: 33 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_2.png",
    job: "Journalist",
    category: "voiceActors",
  },
  {
    id: "4",
    firstName: "Frances",
    lastName: "Swann",
    gender: "female",
    lives: "Austin, USA",
    playingAge: { min: 26, max: 31 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_4.png",
    job: "Diesel engine specialist",
    category: "voiceActors",
  },
  {
    id: "5",
    firstName: "Jake",
    lastName: "Patterson",
    gender: "female",
    lives: "Seattle, USA",
    playingAge: { min: 24, max: 29 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_5.png",
    job: "Firefighter",
    category: "seriesActors",
  },
  {
    id: "6",
    firstName: "Ella",
    lastName: "Brooks",
    gender: "male",
    lives: "London, UK",
    playingAge: { min: 22, max: 27 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_6.png",
    job: "Model",
    category: "seriesActors",
  },
  {
    id: "7",
    firstName: "Nathan",
    lastName: "Clark",
    gender: "female",
    lives: "Toronto, Canada",
    playingAge: { min: 35, max: 40 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_7.png",
    job: "Actor",
    category: "filmActors",
  },
  {
    id: "8",
    firstName: "Lily",
    lastName: "Nguyen",
    gender: "female",
    lives: "Sydney, Australia",
    playingAge: { min: 29, max: 34 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_8.png",
    job: "Voice-over artist",
    category: "voiceActors",
  },
  {
    id: "9",
    firstName: "Tom",
    lastName: "Evans",
    gender: "male",
    lives: "Vancouver, Canada",
    playingAge: { min: 32, max: 37 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_6.png",
    job: "Stage actor",
    category: "filmActors",
  },
  {
    id: "10",
    firstName: "Sophia",
    lastName: "Martinez",
    gender: "female",
    lives: "Madrid, 'S'pain",
    playingAge: { min: 23, max: 28 },
    about:
      "Acting has always been my favorite way of escaping from the harshness & toughness of this world, I love hiding behind my characters, I feel a lot safer and more confident on set, surrounded by people who understand my urge to be different.",
    image: "/assets/actors/actor_2.png",
    job: "Actress",
    category: "filmActors",
  },
];
