export const actors = [
  {
    id: "1",
    firstName: "Autumn",
    lastName: "Phillips",
    gender: "female",
    lives: "New York, USA",
    playingAge: { min: 25, max: 30 },
    about:
      "Autumn is a dedicated psychiatric technician with experience in supporting mental health patients in a variety of settings and roles.",
    image: "/assets/actors/actor_1.png",
    job: "Psychiatric technician",
    category: "filmActors",
  },
  {
    id: "2",
    firstName: "Chris",
    lastName: "Glasser",
    gender: "male",
    lives: "Chicago, USA",
    playingAge: { min: 30, max: 35 },
    about:
      "Chris is an experienced power lineman, known for his attention to detail and commitment to maintaining energy systems safely.",
    image: "/assets/actors/actor_3.png",
    job: "Power lineman",
    category: "seriesActors",
  },
  {
    id: "3",
    firstName: "Kimberly",
    lastName: "Mastran",
    gender: "male",
    lives: "Los Angeles, USA",
    playingAge: { min: 28, max: 33 },
    about:
      "Kimberly has worked as a journalist covering social issues and human interest stories with empathy and insight.",
    image: "/assets/actors/actor_2.png",
    job: "Journalist",
    category: "voiceActors",
  },
  {
    id: "4",
    firstName: "Frances",
    lastName: "Swann",
    gender: "female",
    lives: "Austin, USA",
    playingAge: { min: 26, max: 31 },
    about:
      "Frances specializes in diesel engine maintenance and repair, known for her expertise and technical knowledge in the field.",
    image: "/assets/actors/actor_4.png",
    job: "Diesel engine specialist",
    category: "voiceActors",
  },
  {
    id: "5",
    firstName: "Jake",
    lastName: "Patterson",
    gender: "female",
    lives: "Seattle, USA",
    playingAge: { min: 24, max: 29 },
    about:
      "Jake is a skilled firefighter, devoted to his work and recognized for his bravery in emergency situations.",
    image: "/assets/actors/actor_5.png",
    job: "Firefighter",
    category: "seriesActors",
  },
  {
    id: "6",
    firstName: "Ella",
    lastName: "Brooks",
    gender: "male",
    lives: "London, UK",
    playingAge: { min: 22, max: 27 },
    about:
      "Ella is a model with an international portfolio, noted for her versatility in commercial and high-fashion projects.",
    image: "/assets/actors/actor_6.png",
    job: "Model",
    category: "seriesActors",
  },
  {
    id: "7",
    firstName: "Nathan",
    lastName: "Clark",
    gender: "female",
    lives: "Toronto, Canada",
    playingAge: { min: 35, max: 40 },
    about:
      "Nathan is a seasoned actor known for his strong roles in drama series and passion for complex characters.",
    image: "/assets/actors/actor_7.png",
    job: "Actor",
    category: "filmActors",
  },
  {
    id: "8",
    firstName: "Lily",
    lastName: "Nguyen",
    gender: "female",
    lives: "Sydney, Australia",
    playingAge: { min: 29, max: 34 },
    about:
      "Lily is a voice-over artist with a wide 'r'ange of styles, from animation characters to commercial projects.",
    image: "/assets/actors/actor_8.png",
    job: "Voice-over artist",
    category: "voiceActors",
  },
  {
    id: "9",
    firstName: "Tom",
    lastName: "Evans",
    gender: "male",
    lives: "Vancouver, Canada",
    playingAge: { min: 32, max: 37 },
    about:
      "Tom is an accomplished stage actor known for his dedication to the craft and powerful performances.",
    image: "/assets/actors/actor_6.png",
    job: "Stage actor",
    category: "filmActors",
  },
  {
    id: "10",
    firstName: "Sophia",
    lastName: "Martinez",
    gender: "female",
    lives: "Madrid, 'S'pain",
    playingAge: { min: 23, max: 28 },
    about:
      "Sophia is a budding actress in Spanish cinema, recognized for her natural talent and expressive performances.",
    image: "/assets/actors/actor_2.png",
    job: "Actress",
    category: "filmActors",
  },
];
